[Network]
NATSServerAddress = nats.beyless.com
#ServerPort = 4222
#UseSSL = false
UseNats = true
#SaveJson = false
ListFilePath = /opt/DataFusion/etc/lists.ini

[Boundary255]
Enable = true
P1Lon = 126.548211
P1Lat = 35.939352
P2Lon = 126.548977
P2Lat = 35.939352
P3Lon = 126.549021
P3Lat = 35.938944
P4Lon = 126.548211
P4Lat = 35.938944
